manifest-version = 1

[products.ferrocene]
release = "rolling-2024-06-12"
packages = [
    "rustc-${rustc-host}",
    "rust-std-${rustc-host}",
    "cargo-${rustc-host}",
    "llvm-tools-${rustc-host}",
    "rust-src",
    "rust-std-armv8r-none-eabihf",
]
