[target.aarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tlinker.ld",
    "-Clink-arg=-Tdefmt.x",
]
# QEMU Aarch64 boots in EL1 by default
runner = "qemu-run --machine virt --cpu cortex-a57 --aarch64"

[build]
target = ["aarch64-unknown-none"]

