[package]
edition = "2021"
name = "ffi-use-rust-in-c"
version = "1.0.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
