name: Weekly Canary Build

on:
  schedule:
    - cron: '0 0 * * Mon'


env:
  CARGO_TERM_COLORS: always    # We want colors in our CI output
  CARGO_INCREMENTAL: 0         # Don't waste time writing out incremental build files
  CARGO_PROFILE_TEST_DEBUG: 0  # Same with debug info

jobs:
  weekly-canary-build:
    strategy:
        fail-fast: false
        matrix:
            rust-channel: [stable, beta, nightly]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook@0.4.42,mdbook-graphviz@0.2.1

      - name: Add mdslides
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrous-systems/mdslides/releases/download/v0.5.0/mdslides-installer.sh | sh

      - name: Add graphviz
        run: |
          sudo apt-get update -y && sudo apt-get install -y graphviz

        # `minimal` profile avoids downloading `rustdocs` and other stuff we don't need in CI
        # `--no-self-update` we don't need to update rustup, so we a network trip on that call
      - name: Update and set default Rust
        run: |
          rustup set profile minimal --no-self-update
          rustup update ${{ matrix.rust-channel }} --no-self-update
          rustup default ${{ matrix.rust-channel }} --no-self-update

      - name: Find slug name
        run: |
          slug=$(./describe.sh "${GITHUB_REF}")
          echo "Building with slug '${slug}'"
          echo "slug=${slug}" >> "${GITHUB_ENV}"

      - name: Build book-and-slides
        run: |
          cd ./training-slides && ./build.sh

      - name: Test all cheatsheets
        run: |
          cargo xtask test-all-cheatsheets --locked
